let quotes = [
  "The way you look at me feels like I’m already undressed in your thoughts, as if your eyes are tracing the outline of everything I never dared to say out loud.",
  "Discipline is the real seduction — not everyone can master the art of showing up when no one's watching and still giving it everything.",
  "Your presence doesn’t just light up a room — it shifts the entire atmosphere, like the calm before a storm that promises something unforgettable.",
  "Success begins in silence, in the quiet hours where comfort is sacrificed, and growth happens without applause.",
  "You didn’t touch me, but somehow you left fingerprints on my mind, on my thoughts, and in places only dreams used to go.",
  "True power isn’t loud — it’s found in softness that remains unshaken, in warmth that refuses to turn cold.",
  "Every part of you speaks in a language my body and mind instinctively understand, and I could spend a lifetime learning its dialects.",
  "Rise, even when your legs tremble. Because the moments that shake you the most are the ones that shape you the deepest.",
  "You’re not just attractive — you’re the kind of beautiful that lingers in someone’s mind long after they've stopped looking.",
  "Consistency is the foreplay of greatness. It’s not about how hard you go once — it’s about how often you return with fire.",
  "Your energy enters the room before your footsteps do, and it stays long after you’ve left — haunting, healing, unforgettable.",
  "Focus looks good on you — it’s the kind of confidence that whispers louder than any scream.",
  "You’re not a distraction. You’re the reason I want to become the version of myself I once only dreamed of.",
  "One taste of discipline, and you’ll crave it like a lover — it’s the addiction that rewards in silence.",
  "My favorite place to be is caught between your words and your silence, where meaning hides in the space between.",
  "Chase your goals with the same hunger you chase desire — completely, recklessly, unapologetically.",
  "You make chaos feel like art. I’ve never wanted to lose myself so beautifully before.",
  "Dream big, flirt with risk, and marry the kind of action that turns heads and changes lives.",
  "Every curve, every glance, every hesitation — I want to memorize it all, like a poem too beautiful to forget.",
  "Your quiet wins are the loudest form of revenge — they echo in the places your doubters never expected to hear from again.",
  "I don’t need a map to get lost in you — you’re the kind of mystery I never want solved.",
  "You don’t find time. You seduce it — you make it bend to your will by loving your vision enough to fight for it.",
  "Even your silence keeps me awake at night — it says more than words ever could, and I listen, over and over again.",
  "Success doesn’t flirt with the lazy. It seduces the relentless — the ones who show up even when no one’s clapping.",
  "Your mind is the most intimate place I want to be invited to — thoughts, flaws, fears — all of it.",
  "Don’t dim your fire to make others feel warm — you weren’t made to burn quietly.",
  "You’re not someone I want. You’re someone I crave when everything else has gone quiet.",
  "Fall for someone who doesn’t complete you — but mirrors the ambition and chaos you’ve tamed in yourself.",
  "You’re poetry wrapped in flesh, and I’ve been starving for verses that taste like you.",
  "It’s not about having time — it’s about being so obsessed that you make time irrelevant.",
  "With you, even the silence is heavy, meaningful, and somehow louder than words could ever be.",
  "You shine differently when you stop asking for permission — when you start letting your soul speak in full volume.",
  "I don’t just want to touch you — I want to feel every chapter you’ve ever written inside your mind.",
  "You weren’t born to be soft-spoken. You were made to echo — to remind the world you were here.",
  "Your lips might stay quiet, but your eyes scream stories I want to hear every night before sleep.",
  "Success starts the moment you stop seeking validation — and start giving yourself permission to exist loudly.",
  "One conversation with you feels like a page in a book I never want to reach the end of.",
  "Seduction isn’t in the touch — it’s in the way you make someone feel seen in a world that’s blind.",
  "Turn your heartbreak into a battle cry. Let every scar speak of the nights you refused to break.",
  "You’re the calm in the storm, the chaos in the stillness, and the reason I crave everything I was once afraid of.",
  "You weren’t made to blend in. You were made to be noticed, remembered, and quietly worshipped.",
  "Every time you walk into a room, the world adjusts its frequency to accommodate your presence.",
  "Your ambition doesn’t shout — it whispers in a tone that only those tuned to greatness can hear.",
  "Don’t wait for perfect. Make passionate messes. Let the world see you drenched in your own fire.",
  "You don’t flirt — you rearrange gravity in the room without saying a single word.",
  "Greatness doesn’t knock. It whispers. And only those who are still enough will answer.",
  "I want to learn you like a forbidden book, page by page, understanding that every line could change me forever.",
  "Let your silence carry the weight of the things too powerful for sound.",
  "Some people are sunshine. You’re the entire sky — the dark, the light, the storm, and the stars.",
  "They may forget your words, but they’ll never forget the way you made their soul wake up."
];
